package net.dummythinking.difficultLife;

import cpw.mods.fml.common.*;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.event.FMLServerStartingEvent;
import cpw.mods.fml.common.network.NetworkRegistry;
import cpw.mods.fml.common.network.simpleimpl.SimpleNetworkWrapper;
import cpw.mods.fml.relauncher.Side;
import net.dummythinking.difficultLife.events.DLEventHandler;
import net.dummythinking.difficultLife.init.DLConfigSetup;
import net.dummythinking.difficultLife.init.DLItems;
import net.dummythinking.difficultLife.network.DLPacket;
import net.dummythinking.difficultLife.network.DLPacketHandler;
import net.dummythinking.difficultLife.utils.commands.RegisterCommands;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.common.config.Configuration;

import java.util.ArrayList;

@Mod(
        modid = DLCore.modid,
        name = DLCore.modname,
        version = DLCore.version
)
public class DLCore {

    public static final String modid = "difficultlife";
    public static final String modname = "Difficult Life";
    public static final String version = "1.3.1710.0";

    public static SimpleNetworkWrapper networkManager;

    public static Configuration modCFG;

    @SidedProxy(serverSide = "net.dummythinking.difficultLife.DLServer", clientSide = "net.dummythinking.difficultLife.client.DLClient")
    public static DLServer proxy;

    public static DLCore instance;

    @EventHandler
    public void modPreInit(FMLPreInitializationEvent event) {
        instance = this;
        FMLLog.info("[DifficultLife]Starting pre-initialization phase...", nObj());
        FMLLog.info("[DifficultLife]	*Generating configuration file...", nObj());
        modCFG = new Configuration(event.getSuggestedConfigurationFile());
        DLConfigSetup.setupCFG(modCFG);
        FMLLog.info("[DifficultLife]	*Finished generating configuration file!", nObj());

        networkManager = NetworkRegistry.INSTANCE.newSimpleChannel("DifficultLife");
        networkManager.registerMessage(DLPacketHandler.class, DLPacket.class, 0, Side.SERVER);
        networkManager.registerMessage(DLPacketHandler.class, DLPacket.class, 0, Side.CLIENT);
        NetworkRegistry.INSTANCE.registerGuiHandler(instance, proxy);

        FMLCommonHandler.instance().bus().register(new DLEventHandler());
        MinecraftForge.EVENT_BUS.register(new DLEventHandler());

        DLItems.init();
        DLEventHandler.initPotions();
        proxy.clientInfo();
        ModInfo(event.getModMetadata());
    }

    @EventHandler
    public void serverStart(FMLServerStartingEvent event) {
        new RegisterCommands().initCommands(event.getServer());
    }


    public static Object[] nObj(Object... objects) {
        if (objects != null && objects.length > 0) {
            return objects;
        }

        return new Object[]{};
    }

    public void ModInfo(ModMetadata meta) {
        meta.autogenerated = false;
        meta.modId = modid;
        meta.name = modname;
        meta.version = version;
        meta.description = "Have you ever thought that your game is too easy?\n" +
                "Having a tons of mods installed, and mobs are no longer a threat to you?\n" +
                "Thinking, that armor from some mods (ProjectE) is way too powerfull, and nothing can damage you?\n" +
                "Well then, this mod is for you!";
        meta.credits = "Modbder (Former Author) " +
                "DummyThinking Team";
        ArrayList<String> authors = new ArrayList<String>();
        authors.add("TheMysticDark aka DarkxElocius");
        meta.authorList = authors;
    }
}
